"""[Categories & Transactions]
- Added updated_at column in categories.
- Updated transaction_title to title and transaction_type to type in transactions column.

Revision ID: 4b7f18efcc5b
Revises: b9d729299a1d
Create Date: 2026-08-17 18:42:33.153976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7f18efcc5b'
down_revision: Union[str, Sequence[str], None] = 'b9d729299a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('title', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'transaction_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'title')
    op.drop_column('categories', 'updated_at')
    # ### end Alembic commands ###
