"""updating refresh_tokens table

Revision ID: 60ae1f3dd53b
Revises: 786dffd5fd1d
Create Date: 2026-07-20 20:44:37.125739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ae1f3dd53b'
down_revision: Union[str, Sequence[str], None] = '786dffd5fd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="device_info::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
