"""updated roles model

Revision ID: b9d729299a1d
Revises: 19524d8c4be0
Create Date: 2026-08-05 00:15:40.838163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d729299a1d'
down_revision: Union[str, Sequence[str], None] = '19524d8c4be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('type', sa.String(), nullable=True))
    op.execute("UPDATE roles SET type = 'default' WHERE type IS NULL")
    op.alter_column("roles", "type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'type')
    # ### end Alembic commands ###
